---
- name: open node_exporter firewall port
  firewalld:
    port: "{{ node_exporter_port }}/tcp"
    zone: "public"
    permanent: true
    immediate: true
    state: enabled
- name: make collector directory
  file:
    path: "{{ node_exporter_collector_dir }}"
    state: directory
- name: include setup_container.yml
  include_tasks: setup_container.yml
