---
- name: set fact container_binary to docker centos 7
  set_fact: 
    container_binary: "docker"
  when:
    - ansible_distribution is 'CentOS'
    - ansible_distribution_major_version is '7'

- name: set fact container_binary to docker debian
  set_fact: 
    container_binary: "docker"
  when:
    - ansible_distribution is 'Debian'

- name: ship systemd service
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0644

- name: start the node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  failed_when: false
