---
- name: open znapzend_exporter firewall port
  firewalld:
    port: "{{ znapzend_exporter_port }}/tcp"
    zone: "public"
    permanent: true
    immediate: true
    state: enabled

- name: include setup_container.yml
  include_tasks: setup_container.yml

- name: install helper scripts
  block:
    - name: create znapzend dir
      ansible.builtin.file:
        path: /opt/znapzend
        state: directory
        mode: '0755'
    
    - name: Copy helper scripts
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/znapzend/{{ item }}
        owner: root
        group: root
        mode: '0774'
      loop:
        - pre_send_cmd.sh
        - post_send_cmd.sh
        - pre_snap_cmd.sh
        - post_snap_cmd.sh
        - error_logger

    - name: Copy znapzend cron file
      ansible.builtin.copy:
        src: "error_logger"
        dest: /etc/cron.d/error_logger
        owner: root
        group: root
        mode: '0774'
