---
- name: open znapzend_exporter firewall port
  firewalld:
    port: "{{ znapzend_exporter_port }}/tcp"
    zone: "public"
    permanent: true
    immediate: true
    state: enabled

- name: include setup_container.yml
  include_tasks: setup_container.yml
