---
- name: ship systemd service
  template:
    src: znapzend_exporter.service.j2
    dest: "/etc/systemd/system/znapzend_exporter.service"
    owner: root
    group: root
    mode: 0644

- name: start the znapzend_exporter service
  systemd:
    name: znapzend_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  failed_when: false
