{
 "title": "Mdadm Overview",
 "description": "Prometheus node_exporter mdadm module dashboard. Per Server and global view.",
 "tags": [
  "node",
  "disk",
  "mdstat"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info{job=~\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Disks",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_md_is_active{instance=~\"$node\"}) / count(node_md_is_active{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Installed Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$node\"}) / count(node_md_disks{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Active Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_md_disks_active{instance=~\"$node\"}) / count(node_md_disks_active{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Block Sync Ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_md_blocks_synced{instance=~\"$node\"}) / count(node_md_blocks_synced{instance=~\"$node\"})) / (sum(node_md_blocks{instance=~\"$node\"}) / count(node_md_blocks{instance=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Sync State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_md_blocks{instance=~\"$node\"}) / count(node_md_blocks{instance=~\"$node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_md_blocks_synced{instance=~\"$node\"}) / count(node_md_blocks_synced{instance=~\"$node\"})",
     "legendFormat": "Synced"
    }
   ]
  }
 ]
}