{
 "title": "ZFS Replication Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Space Used by Dataset (Source)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "zfs_dataset_used_bytes", "legendFormat": "__auto" },
    {
     "expr": "zfs_dataset_used_by_snapshot_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "zfs_dataset_referenced_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Space Used by Dataset (Destination)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "zfs_dataset_used_bytes", "legendFormat": "__auto" },
    {
     "expr": "zfs_dataset_used_by_snapshot_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "zfs_dataset_referenced_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replication Task State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "znapzend_presend_command_started",
     "legendFormat": "{{exported_job}} Active"
    }
   ]
  },
  {
   "title": "Data Written Since Last Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_dataset_written_bytes{instance=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (device) (\n  irate(node_network_receive_bytes{device!=\"lo\"}[1m]) or \n  irate(node_network_receive_bytes_total{device!=\"lo\"}[1m])\n)",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (\n  irate(node_network_transmit_bytes{device!=\"lo\"}[1m]) or\n  irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])\n)",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "Total Write"
    },
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "Total Read"
    }
   ]
  }
 ]
}