{
 "title": "ZFS Stats Overview",
 "description": "Graphs ZFS ARC and ARC L2 Hit %, Hits, Misses, Size, and Zpool",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info{job=~\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_rtime{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(node_zfs_zpool_wtime{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_reads{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "irate(node_zfs_zpool_writes{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "Writes"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ARC - Hit %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node\",instance=\"$node\"}[5m]) / (irate(node_zfs_arc_demand_data_hits{job=\"node\",instance=\"$node\"}[5m]) + irate(node_zfs_arc_demand_data_misses{job=\"node\",instance=\"$node\"}[5m])) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node\",instance=\"$node\"}[5m]) / (irate(node_zfs_arc_demand_metadata_hits{job=\"node\",instance=\"$node\"}[5m]) + irate(node_zfs_arc_demand_metadata_misses{job=\"node\",instance=\"$node\"}[5m])) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - Hits, Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "metadata_misses"
    }
   ]
  },
  {
   "title": "ARC - Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{job=\"node\",instance=\"$node\"}",
     "legendFormat": "data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{job=\"node\",instance=\"$node\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{job=\"node\",instance=\"$node\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_zfs_arc_hdr_size{job=\"node\",instance=\"$node\"}",
     "legendFormat": "hdr"
    },
    {
     "expr": "node_zfs_arc_other_size{job=\"node\",instance=\"$node\"}",
     "legendFormat": "other"
    }
   ]
  },
  { "title": "L2ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "L2ARC - Hit %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{job=\"node\",instance=\"$node\"}[5m]) / (irate(node_zfs_arc_l2_hits{job=\"node\",instance=\"$node\"}[5m]) + irate(node_zfs_arc_l2_misses{job=\"node\",instance=\"$node\"}[5m])) * 100",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "L2ARC - Hits, Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(node_zfs_arc_l2_misses{job=\"node\",instance=\"$node\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "L2ARC - Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_l2_asize{job=\"node\",instance=\"$node\"}",
     "legendFormat": "asize"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{job=\"node\",instance=\"$node\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_l2_size{job=\"node\",instance=\"$node\"}",
     "legendFormat": "size"
    }
   ]
  }
 ]
}