groups:
- name: zfs
  rules:
  - alert: ZpoolDegradedState
    expr: node_zfs_zpool_state{state="degraded"} == 1
    labels:
      severity: warning
    annotations:
      summary: "Attention Required: {{ $labels.instance }} : zpool {{ $labels.zpool }} is in a {{ $labels.state }} state."
      description: "Zpool:{{ $labels.zpool }} has experienced a failure but is still functioniong. The fault tolerance of the pool might be compromised, as a subsequent fault in another device might be unrecoverable"
  - alert: ZpoolFaultedState
    expr: node_zfs_zpool_state{state="faulted"} == 1
    labels:
      severity: critical
    annotations:
      summary: "Attention Required: {{ $labels.instance }} : zpool {{ $labels.zpool }} is in a {{ $labels.state }} state."
      description: "Zpool:{{ $labels.zpool }} is in FAULTED state and is completely inaccessible. No data can be recovered until the necessary devices are attached or repaired"
  - alert: ZFS Send Task Started
    expr: deriv(znapzend_presend_command_started[1m]) > 0
    labels:
      severity: info
    annotations:
      summary: "ZFS Snapshot Send Started : Dataset {{ $labels.exported_job }} has started a replication task"
      description: "Dataset:{{ $labels.exported_job }} has started a replication task from host {{ $labels.instance }} to remote destination {{ $labels.target_host }} "
  - alert: ZFS Send Task Finished
    expr: deriv(znapzend_presend_command_started[1m]) < 0
    labels:
      severity: info
    annotations:
      summary: "ZFS Snapshot Send finished: Dataset {{ $labels.exported_job }} has finished a replication task"
      description: "Dataset:{{ $labels.exported_job }} has finished a replication task from host {{ $labels.instance }} to remote destination {{ $labels.target_host }} "
  - alert: ZFS Send Task Failed
    expr: znapzend_job_failed == 1
    labels:
      severity: warn
    annotations:
      summary: "ZFS Snapshot Send failed: Dataset {{ $labels.source_dataset }} has failed to send"
      description: "Dataset:{{ $labels.source_dataset }} has failed its replication task from host {{ $labels.instance }} to remote destination {{ $labels.target_host }}. Please consult 'journalctl -u znapzend' on host {{ $labels.instance }} for reason"
  - alert: Znapzend Service Failed
    expr: node_systemd_unit_state{name="znapzend.service",state="active"} == 0
    for: 1m
    labels: 
      severity: critical
    annotations:
      summary: "Znapzend systemd service failed or is not running" 
      description: "Znapzend service is not running, check systemctl status or journalctl for more information"    
